name: Telegram News Bot

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 * * * *'  # Runs every hour (restart every hour to prevent failures)

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 55  # Let the script run for 55 minutes before restarting
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install feedparser googletrans==4.0.0-rc1 python-telegram-bot jdatetime requests beautifulsoup4

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python news_bot.py